Led/urls.py
from django.urls import path
from .views import index
from Led import views

app_name = "loginpage"
urlpatterns = [
    path('login', views.loginpage, name='login'),
    path('logout', views.logoutpage, name='logout'),
    path('home', views.home, name='home'),
    path('homepage', views.homepage.as_view(), name="homepage"),
    path('api/data', views.getAllDataAPIVIEW.as_view(), name="api-data"),
    path('export', views.ExPortCSV, name='export'),
    path('dgt', views.dengiaothong, name='dgt'),
]

Led_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Led.urls'))
]

jokes_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jokes.urls'))
]

Led/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class data(models.Model):
    # title = models.CharField(max_length=255)
    price = models.IntegerField(default=0)
    # content= models.CharField(max_length=255)
    joindate = models.DateField()
    # created_at = models.DateTimeField()
class Sensor(models.Model):
    temperature = models.FloatField(default=0)
    humidity = models.FloatField(default=0)
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "Nhiệt độ: " f"{self.temperature}" + " Độ ẩm: " f"{self.humidity}" + " Thời gian: " f"{self.timestamp}"

Led/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import View
from django.contrib.auth.views import LoginView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from ClassMqtt import ClassMqtt
import json
from random import randint
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import data
from .serializers import getAllData
import csv


list_Data = ''
# Create your views here.
def index(request):
    return render(request, 'login.html')


class homepage(View):
    def get(self, request):
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            number = randint(1, 10)
            return JsonResponse({'number': number})
        return render(request, "home.html")

    def post(seft, request):
        data = json.loads(request.body)
        float_number = float(data['number'])
        print(float_number)
        return JsonResponse({'float': f'you got: {float_number}'})


@login_required(login_url="/login")
def home(request):
    if request.method == "POST":
        data = json.loads(request.body)
        # abc = data['number']
        sendMqtt = ClassMqtt()
        sendMqtt.publishmqtt('Test', data)
        print(data)
        return JsonResponse(data)
    if request.method == "GET":
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            number = randint(1, 10)
            return JsonResponse({'number': number})
        return render(request, "home.html")
    # return render(request, "home.html")


def loginpage(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/home')
        else:
            messages.error(request, '!Tên đăng nhập hoặc mật khẩu không chính xác')
    context = {}
    return render(request, "login.html", context)


def logoutpage(request):
    logout(request)
    return redirect('/login')

class getAllDataAPIVIEW(APIView):
    def get(self, request):
        list_Data = data.objects.all()
        mydata = getAllData(list_Data, many=True)
        return Response(data= mydata.data, status=status.HTTP_200_OK)

    def post(self, request):
        # date = json.loads(request.data)
        date = request.data
        startDate = date['StartDate']
        endDate = date['EndDate']
        list_Data = data.objects.raw('SELECT * FROM led_data WHERE joindate BETWEEN "'+startDate+'" AND "'+endDate+'" ;')
        mydata = getAllData(list_Data, many=True)
        return Response(data= mydata.data, status=status.HTTP_200_OK)

@login_required(login_url="/login")
def ExPortCSV(request):
    if request.method == "POST":
        startDate = request.POST.get('startdate')
        endDate = request.POST.get('enddate')
        list_Data = data.objects.raw('SELECT * FROM led_data WHERE joindate BETWEEN "' + startDate + '" AND "' + endDate + '" ;')
        mydata = getAllData(list_Data, many=True)

        responce = HttpResponse(content_type='text/csv')
        writer = csv.writer(responce)
        writer.writerow(['Value','Date'])
        for value in list_Data:
            writer.writerow([value.price, value.joindate])
        responce['Content-Disposition'] = 'attachment; filename = "ExPortData.csv"'
        return responce

    if request.method == "GET":
        responce = HttpResponse(content_type='text/csv')
        writer = csv.writer(responce)
        writer.writerow(['Value', 'Date'])
        for value in data.objects.all().values_list('price','joindate'):
            writer.writerow(value)
        responce['Content-Disposition'] = 'attachment; filename = "ExPortData.csv"'
        return responce

def dengiaothong(request):
    context = {}
    return render(request, "DGT.html", context)

templates/DGT.html
{% extends 'base.html' %}
{% block DGT %}
{% load static %}
<div class="pt-4 mt-4 d-flex justify-content-between"></div>

<div class="mt-4">
    <div class="center card background">
        <div id="DGT" class="window center">
            <div class="d-flex flex-wrap align-content-start" style="height:50%; width:100%;">
                <div class="row d-flex justify-content-between" style="width:100%;">
                    <div class="col-4 row">
                        <h2 class="text-success"><b>TUYẾN 1</b></h2>
                        <div class="col-9">
                            <img src="static/images/DGT/do1false.png" class="do1" alt="Cinque Terre" width="50" height="50">
                            <img src="static/images/DGT/vang1false.png" class="vang1" alt="Cinque Terre" width="50" height="50">
                            <img src="static/images/DGT/xanh1false.png" class="xanh1" alt="Cinque Terre" width="50" height="50">
                            <img src="static/images/DGT/xanhbo1false.png" class="xanhbo1" alt="Cinque Terre" width="50" height="50">
                            <img src="static/images/DGT/dobo1false.png" class="dobo1" alt="Cinque Terre" width="50" height="50">
                        </div>
                        <div class="col-3 d-flex flex-wrap align-content-center">
                            <div class="demnguoch1 card " style="font-size: 2.3em; border: 0px solid rgba(0, 0, 0, 0.125);">999</div>
                        </div>
                    </div>
                    <div class="col-4 row">
                        <h2 class="text-success"><b>TUYẾN 2</b></h2>
                        <div class="col-9">
                            <img src="static/images/DGT/do2false.png" class="do2" alt="Cinque Terre" width="50" height="50">
                            <img src="static/images/DGT/vang2false.png" class="vang2" alt="Cinque Terre" width="50" height="50">
                            <img src="static/images/DGT/xanh2false.png" class="xanh2" alt="Cinque Terre" width="50" height="50">
                            <img src="static/images/DGT/xanhbo2false.png" class="xanhbo2" alt="Cinque Terre" width="50" height="50">
                            <img src="static/images/DGT/dobo2false.png" class="dobo2" alt="Cinque Terre" width="50" height="50">
                        </div>
                        <div class="col-3 d-flex flex-wrap align-content-center">
                            <div class="demnguoch2 " style="font-size: 2.3em; border: 0px solid rgba(0, 0, 0, 0.125);">999</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="d-flex flex-wrap align-content-end" style="height:50%; width:100%;">
                <div class="row d-flex justify-content-between" style="width:100%;">
                    <div class="col-4 row">
                        <h2 class="text-success"><b>TUYẾN 2</b></h2>
                        <div class="col-9">
                            <img src="static/images/DGT/do2false.png" class="do2" alt="Cinque Terre" width="50" height="50">
                            <img src="static/images/DGT/vang2false.png" class="vang2" alt="Cinque Terre" width="50" height="50">
                            <img src="static/images/DGT/xanh2false.png" class="xanh2" alt="Cinque Terre" width="50" height="50">
                            <img src="static/images/DGT/xanhbo2false.png" class="xanhbo2" alt="Cinque Terre" width="50" height="50">
                            <img src="static/images/DGT/dobo2false.png" class="dobo2" alt="Cinque Terre" width="50" height="50">
                        </div>
                        <div class="col-3 d-flex flex-wrap align-content-center">
                            <div class="demnguoch2" style="font-size: 2.3em; border: 0px solid rgba(0, 0, 0, 0.125);">999</div>
                        </div>
                    </div>
                    <div class="col-4 row d-flex justify-content-end">
                        <h2 class="text-success ps-4"><b>TUYẾN 1</b></h2>
                        <div class="col-9">
                            <img src="static/images/DGT/do1false.png" class="do1" alt="Cinque Terre" width="50" height="50">
                            <img src="static/images/DGT/vang1false.png" class="vang1" alt="Cinque Terre" width="50" height="50">
                            <img src="static/images/DGT/xanh1false.png" class="xanh1" alt="Cinque Terre" width="50" height="50">
                            <img src="static/images/DGT/xanhbo1false.png" class="xanhbo1" alt="Cinque Terre" width="50" height="50">
                            <img src="static/images/DGT/dobo1false.png" class="dobo1" alt="Cinque Terre" width="50" height="50">
                        </div>
                        <div class="col-3 d-flex flex-wrap align-content-center">
                            <div class="demnguoch1" style="font-size: 2.3em; border: 0px solid rgba(0, 0, 0, 0.125);">999</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<button onclick="DGT()">DGT</button>
<script src="{% static 'js/DGT.js' %}"></script>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tuan</title>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link href="{% static 'Bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'Bootstrap/js/bootstrap.bundle.js' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/switch.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/button.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/DGT.css' %}">
</head>
<body>
<nav class="fixed-top">
    <ul class="globalmenu" id="navbar">
        <li><a href="{% url 'loginpage:home' %}">home</a></li>
        <li><a href="http://127.0.0.1:8000/admin">Admin</a></li>
        <li><a href="{% url 'loginpage:dgt' %}">Đèn Giao Thông</a></li>
        <li><a href="#alarm">alarm</a></li>
        <li><a href="#contact">contact</a></li>
<!--        <li class="alignright"><a href="{% url 'loginpage:login' %}">Đăng nhập</a></li>-->
        <li class="alignright"><a href="{% url 'loginpage:logout' %}">Đăng xuất</a></li>
        <li class="dropdownicon"><a onclick="tuanthegioi()">&#9776;</a></li>
        <li class="alignright"><a class="bi bi-person">:  {{request.user}}</a></li>
    </ul>
</nav>



<div class="content">
    {% block Login %}

    {% endblock %}
</div>
<div class="content">
    {% block Home %}

    {% endblock %}
</div>

<div class="content">
    {% block DGT %}

    {% endblock %}
</div>
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
<script src="{% static 'js/base.js' %}"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block Home %}
{% load static %}
<div class="row m-2 pt-5">
    <div class="col-md-8">
        <div class="card p-3 mb-3" style="height:516px">
            <div class="d-flex justify-content-between row">
                <div class="col-sm-4"><h4>Bảng Thống Kê</h4></div>
                <div class="d-flex justify-content-end col-sm-8" >
                    <div class="d-flex justify-content-end">
                        <form action="/export" method="post">
                            {% csrf_token %}
                            <input type="date" id="startdate" value="2023-05-08" name="startdate">
                            <input class="" type="date" id="enddate" value="2023-05-14" name="enddate">
                            <div class="btn" onclick="abc()" style="font-size: 1.5em;"><ion-icon name="search-outline"></ion-icon></div>
                            <button class="btn" type="submit"><ion-icon name="print-outline" style="font-size: 1.5em;"></ion-icon></button>
                        </form>
                    </div>

                </div>
            </div>
            <hr>
            <canvas class="chart-container mb-3" style="position: relative; height:100%; width:100%" id="myChart1"></canvas>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card p-3 mb-3" style="height:161.3px">
            <h4>Nhiệt Độ</h4>
            <hr>
            <div class="d-flex justify-content-between">
                <h2 id="nhietdo"></h2>
                <div style="font-size: 2.4em;">
                    <ion-icon name="sunny-outline"></ion-icon>
                </div>
            </div>
        </div>
        <div class="card p-3 mb-3" style="height:161.3px">
            <h4>Độ Ẩm</h4>
            <hr>
            <div class="d-flex justify-content-between">
                <h2 id="doam"></h2>
                <div style="font-size: 2em;">
                    <ion-icon name="water-outline"></ion-icon>
                </div>
            </div>
        </div>
        <div class="card p-3 mb-3" style="height:161.3px;">
            <h4>Tên Thiết Bị</h4>
            <hr>
            <br>
            <div class="d-flex justify-content-between">
                <h4 id="textbox">GT070E</h4>
                <div id="icon" style="font-size: 1.8em; color: black;">
                    <ion-icon name="desktop-outline"></ion-icon>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row m-2">
    <div class="col-md-4 mb-3">
        <div class="d-flex justify-content-center">
            <div class="card" style="height:300px; width:100%">
                <div class="card-body" style="position: relative; height:100%; width:100%">
                        <h4>Bảng Điều Khiển</h4>
                        <hr>
                        <input class="switch" type="checkbox" id="switch1" onclick="bulbToggle()" name="light"/><label class="switchlb"
                                                                                                          for="switch1" >Toggle</label>
                        <img src="static/images/lightoff.jpg" class="img-fluid mx-auto d-block mt-5" alt="Cinque Terre"
                             width="50" height="80" id="lightbulb">
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 mb-3">
        <div class="d-flex justify-content-center">
            <div class="card" style="height:300px; width:100%">
                <div class="card-body" style="position: relative; height:100%; width:100%">
                    <h4>Bảng Điều Khiển</h4>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <div>
                            {% csrf_token %}
                            <button class="custom-btn btn-4" onclick="getNumber()"><span>Bật</span></button>
                            <button class="custom-btn btn-5" onclick="getFloatNumber()"><span>Tắt</span></button>
                        </div>
                        <div><input type="number" class="input-group mt-2" id="ItemValue4" placeholder=" Timer(s)" name="timer" onchange="timer()"></div>
                    </div>
                    <div id="ItemValue1"></div>
                    <img src="static/images/lightoff.jpg" class="img-fluid mx-auto d-block mt-5" alt="Cinque Terre"
                         width="50" height="80" id="lightbulb1">
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 mb-3">
        <div class="d-flex justify-content-center">
            <div class="card" style="height:300px; width:100%">
                <div class="card-body" style="position: relative; height:100%; width:100%">
                    <h4>Biểu Đồ</h4>
                    <hr>
                    <canvas class="chart-container" style="position: relative; height:80%; width:100%" id="myChart"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>
<!--<div class="frame">-->
<!--    <button class="custom-btn btn-1">Read More</button>-->
<!--    <button class="custom-btn btn-2">Read More</button>-->
<!--    <button class="custom-btn btn-3"><span>Read More</span></button>-->
<!--    <button class="custom-btn btn-4"><span>Read More</span></button>-->
<!--    <button class="custom-btn btn-5"><span>Read More</span></button>-->
<!--    <button class="custom-btn btn-6"><span>Read More</span></button>-->
<!--    <button class="custom-btn btn-7"><span>Read More</span></button>-->
<!--    <button class="custom-btn btn-8"><span>Read More</span></button>-->
<!--    <button class="custom-btn btn-9">Read More</button>-->
<!--    <button class="custom-btn btn-10">Read More</button>-->
<!--    <button class="custom-btn btn-11">Read More-->
<!--        <div class="dot"></div>-->
<!--    </button>-->
<!--    <button class="custom-btn btn-12"><span>Click!</span><span>Read More</span></button>-->
<!--    <button class="custom-btn btn-13">Read More</button>-->
<!--    <button class="custom-btn btn-14">Read More</button>-->
<!--    <button class="custom-btn btn-15">Read More</button>-->
<!--    <button class="custom-btn btn-16" onclick="abc()">abc</button>-->
<!--</div>-->

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{% static 'js/app.js' %}"></script>
<script src="{% static 'js/ajax.js' %}"></script>
<script src="{% static 'js/light.js' %}"></script>
<script src="{% static 'js/Chart.js' %}"></script>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tuan</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<div class="container p-5 my-5 bg-dark text-white">
    <h1 id="jokes"></h1>
</div>
<div class="container p-5 my-5 bg-dark text-white">
    <h1 id="mqtt"></h1>
</div>
<div class="container p-5 my-5 bg-dark text-white">
    <h1 id="ItemValue1"></h1>
</div>
<div class="container p-5 my-5 bg-dark text-white">
    <h1 id="ItemValue2"></h1>
</div>
<div class="container p-5 my-5 bg-dark text-white">
    <h1 id="ItemValue3"></h1>
</div>
<div class="container p-5 my-5 bg-dark text-white">
    <h1 id="ItemValue4"></h1>
</div>
<script>
    var socket = new WebSocket('ws://localhost:8000/ws/Led/');
    socket.onmessage = function(event){
    var joke = event.data;
    console.log("Message from server ", event.data);
    document.querySelector('#jokes').innerText = joke;
    }

    var socket = new WebSocket('ws://localhost:8000/ws/Mqtt/');
    socket.onmessage = function(event){
    const mqtt = event.data;
    console.log(event.data);
    document.querySelector('#mqtt').innerText = mqtt;

    const massage = JSON.parse(mqtt)
    for (let x in massage) {
        console.log(massage[x]);
        document.querySelector('#'+x).innerText = massage[x];
        }
    }
</script>
</body>
</html>

templates/login.html
{% extends 'base.html' %}
<!--{% block title %} Đăng Nhập {% endblock %}-->
{% block Login %}
<div>
    <div class="container w-40 mt-5 pt-5">
        <div class="row template justify-content-center border rounded-4 shadow p-2">
            <div class="col-lg-6">
                <div class="d-flex justify-content-center mt-4 shadow p-1">
                    <div class="p-2"><img src="static/images/logoTMK.png" class="img-fluid mx-auto d-block" alt="Cinque Terre"
                              width="60" height="55"></div>
                    <div class="text-center text-info fs-2 mt-3 p-1">TMK WEBAPP</div>
                </div>
                <img src="static/images/login.png" class="img-fluid mx-auto mt-5" alt="Cinque Terre" width="600" height="550">
                <hr class="d-sm-none">
            </div>
            <div class="col-lg-6">
                <div class="border-start">
                    <div class="container mt-4 mb-3">
                        <div><p class="text-center text-info fs-2 mt-2 shadow p-4">ĐĂNG NHẬP</p></div>
                        <img src="static/images/login3.png" class="img-fluid mx-auto d-block mt-5" alt="Cinque Terre" width="190"
                             height="130">
                        <form action="{% url 'loginpage:login' %}" method="post" class="fs-4">
                            {% csrf_token %}
<!--                            {{ form.as_p }}-->
                            <div class="mb-3 mt-5 ">
                                <label for="taikhoan">Tài khoản:</label>
                                <input type="text" class="form-control fs-4 mt-2" id="taikhoan"
                                       placeholder="Vùi lòng nhập tài khoản"
                                       name="username">
                            </div>
                            <div class="mb-4">
                                <label for="pwd">Mật khẩu:</label>
                                <input type="password" class="form-control fs-4 mt-2" id="pwd"
                                       placeholder="Vui lòng nhập mật khẩu"
                                       name="password">
                            </div>

                            {% for message in messages %}
                                <p class="alert alert-warning">{{ message }}</p>
                            {% endfor %}

                            <div class="form-check mb-3">
                                <label class="form-check-label">
                                    <input class="form-check-input mt-0" type="checkbox" name="remember"> Nhớ tài khoản
                                </label>
                            </div>
                            <button type="submit" class="custom-btn btn-3"><span>Đăng Nhập</span></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="mt-5 p-4 bg-dark text-white text-center" id="page-bottom">
    <p class="">CÔNG TY TNHH KỸ THUẬT TMK</p>
    <p class="">MST: 0313 011 680</p>
    <p class="">Địa chỉ đăng ký: 76/89A Phan Tây Hồ, Phường 7, Quận Phú Nhuận, TP. HCM</p>
    <p class="">Địa Chỉ giao dịch: 112 Đường 18B, P. Bình Hưng Hòa A, Quận Bình Tân, TP. HCM</p>
    <p class="">Phone: 0909 167 148</p>
    <p class="">Email: tmktek@gmail.com</p>
</div>
{% endblock %}